//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int id_pedido { get; set; }
        public string pedido_costo { get; set; }
        public string pedido_descripcion { get; set; }
        public Nullable<int> pedido_id_relacion_productos_por_pedido { get; set; }
        public Nullable<int> pedido_id_usuario { get; set; }
        public string pedido_nombre_cliente { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual relacion_productos_por_pedido relacion_productos_por_pedido { get; set; }
    }
}
