//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int id_permiso { get; set; }
        public Nullable<int> permiso_id_rol { get; set; }
        public Nullable<int> permiso_id_pantalla { get; set; }
    
        public virtual pantallas pantallas { get; set; }
        public virtual roles roles { get; set; }
    }
}
