//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacion_productos_por_pedido
    {
        public int id_relacion_productos_por_pedido { get; set; }
        public Nullable<int> relacion_productos_por_pedido_id_producto { get; set; }
        public Nullable<int> relacion_productos_por_pedido_id_pedido { get; set; }
    
        public virtual pedidos pedidos { get; set; }
        public virtual productos productos { get; set; }
    }
}
